"use client";

import { useState } from "react";
import { DataSummary, Overview } from "@/lib/data";

export default function Methodology({ data, overview }: { data: DataSummary; overview: Overview }) {
  const [open, setOpen] = useState(false);

  return (
    <section className="section-pad method-section" id="methodology">
      <div className="wrap">
        <div className="section-intro">
          <span className="eyebrow">Methodology · Auditable, not dominant</span>
          <h2>How the lab was built</h2>
          <p>{data.source_summary} Every number on this page is generated by the Python research engine and read from JSON — nothing here is hand-written.</p>
        </div>

        <div className="method-grid">
          <div className="panel method-card">
            <div className="mc-label mono">Data & universe</div>
            <ul className="mc-list">
              <li><b>{data.universe.length}</b> liquid ETFs · {data.asset_groups.length} asset groups</li>
              <li>Price panel {data.sample_period.start} → {data.sample_period.end}</li>
              <li>Backtest calendar from {data.backtest_period.start}</li>
              <li>Returns from {data.return_basis}</li>
              <li>Sources: {data.sources.join(", ")}</li>
            </ul>
          </div>
          <div className="panel method-card">
            <div className="mc-label mono">No look-ahead & cash</div>
            <p className="mc-body">{data.no_lookahead_rule}</p>
            <p className="mc-body" style={{ marginTop: 10 }}>{data.cash_handling}</p>
            <div className="mc-rule mono">{data.primary_strategy_rules.join(" · ")}</div>
          </div>
          <div className="panel method-card">
            <div className="mc-label mono">Cost model & turnover</div>
            <p className="mc-body">{data.cost_model.description}</p>
            <div className="mc-costs">
              {data.cost_model.scenarios.map((s) => (
                <span key={s.scenario} className={`mc-cost ${s.cost_bps === data.cost_model.primary_cost_bps ? "primary" : ""}`}>
                  {s.cost_bps} bps
                </span>
              ))}
            </div>
            <p className="mc-body" style={{ marginTop: 10, fontSize: "12.5px" }}>{data.cost_model.turnover_definition}</p>
            <p className="mc-foot mono">Primary reported cost: {data.cost_model.primary_cost_bps} bps</p>
          </div>
          <div className="panel method-card">
            <div className="mc-label mono">Validation</div>
            <ul className="mc-list">
              <li>Train {data.train_test_split.train}</li>
              <li>Test {data.train_test_split.test}</li>
              <li>{data.walk_forward_windows} expanding walk-forward windows</li>
              <li>Cost · parameter · rebalance · regime · crisis stress</li>
            </ul>
            <p className="mc-body" style={{ marginTop: 10, fontSize: "12.5px" }}>{data.regime_note}</p>
          </div>
        </div>

        <button className="method-toggle" aria-expanded={open} onClick={() => setOpen(!open)}>
          {open ? "Hide" : "Show"} the full universe & limitations
          <span className="mt-caret">{open ? "▲" : "▼"}</span>
        </button>

        {open && (
          <div className="method-detail panel">
            <div className="md-cols">
              <div>
                <div className="mc-label mono">Universe — {data.universe.length} ETFs, all included</div>
                <table className="universe-table">
                  <thead><tr><th>Ticker</th><th>Asset</th><th>Group</th><th>First</th><th>Last</th><th>Source</th></tr></thead>
                  <tbody>
                    {data.universe.map((a) => (
                      <tr key={a.ticker}>
                        <td className="mono">{a.ticker}</td><td>{a.name}</td>
                        <td className="ut-group">{a.group.replace(/_/g, " ")}</td>
                        <td className="mono">{a.first_date.slice(0, 7)}</td>
                        <td className="mono">{a.last_date.slice(0, 7)}</td>
                        <td className="mono ut-src">{a.source}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
                <p className="md-excl">{data.sample_period.note}</p>
                {data.excluded_assets.length > 0 && (
                  <p className="md-excl">Excluded: {data.excluded_assets.join(", ")}</p>
                )}
              </div>
              <div>
                <div className="mc-label mono">Benchmarks</div>
                <ul className="mc-list">{data.benchmarks.map((b) => <li key={b.key}>{b.name}</li>)}</ul>
                <div className="mc-label mono" style={{ marginTop: 22 }}>Limitations</div>
                <ul className="mc-list muted">{data.limitations.map((l, i) => <li key={i}>{l}</li>)}</ul>
              </div>
            </div>
          </div>
        )}
      </div>
    </section>
  );
}
